[package]
name = "rusty_webview"
version = "0.1.0"
authors = ["outcastgeek"]
edition = "2018"

[dependencies]
web-view = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
lazy_static = "1.3"
tera = "0.11"
